### PR TITLE
V2 - Deprecated FCM APIs, add FCM method (HTTP v1 new API)

### PR DESCRIPTION
**Pull request by wcalebgray**
From PR #194 , this copies over the code and fixes the tests (mostly ramda failing)

Exactly none of this has been tested so far.

### CODE REVIEW

**Comment by giantslogik** [comment]
@wcalebgray  there an ETA on this or a linked issue?

**Comment by giantslogik** [comment]
@alex-friedl @wcalebgray I'll try and test the PR for my usecase. I've also created https://github.com/appfeel/node-pushnotifications/issues/208 to keep users informed of the issue / resolution.

**Review by alex-friedl — APPROVED** [review]

**Comment by alex-friedl** [comment]
Merging this in order to fix linter and doc issues and prepare a release

**Comment by giantslogik** [comment]
@alex-friedl how are the typescript definitions maintained ? I'm using @types/node-pushnotifications , and don't see the FCM API there.
cc: @wcalebgray

**Pull request merged**
