### PR TITLE
Error response as string for compatibility with JSON.stringify

### PR DESCRIPTION
**Pull request by alex-friedl**

### CODE REVIEW

**Comment by alex-friedl** [comment]
@appfeel This should fix the recurring issues in #34 #38 etc. 
But it could break some applications that have a workaround in place which can only `Error` instances. These could be easily adapted or fixed though ...

**Comment by miqmago** [comment]
Hi @alex-friedl, last week I found myself placing console.log in `apn`...

When I developed the error management at first long ago, my purpose was to standardize the response, not to have `Error` objects and `string` objects depending on the provider or the error itself, so that the error management could be done always the same way.

Do you think it's better to give always an string than an error? I'm not really understanding why it's needed to convert it to string, maybe if we could maintain as `Error` object it would not break previous versions? Otherwise, if this is the only way to do it, I would release it as a minor version change.

The responses from apn are like this right now:

**Success**:
```json
{
    "sent": [{ "device": "1ff4aac313136dc3..." }],
    "failed": []
}
```

**Error**:

```json
{
    "sent": [],
    "failed": [
        {
            "device": "1ff4aac313136dc3...",
            "status": "400",
            "response": {
                "reason": "BadDeviceToken"
            }
        }
    ]
}
```

The point here is I'm not understanding why this is not working:

    error: new Error(failure.response.reason || failure.response)

Another think that we could do to maintain the compatibility is to keep error as it is (maybe reviewing the cases where it does not return an string) and introduce another parameter to the response with the code when needed...

**Comment by alex-friedl** [comment]
Hi @miqmago ,

I think the issue is related to https://stackoverflow.com/questions/18391212/is-it-not-possible-to-stringify-an-error-using-json-stringify. 
objects of type 'Error` are not properly deserialized by `JSON.stringify`.
I am not sure about how to proceed. I think the change should not break many applications unless they have very naive implementations for deeply logging the responses.

**Comment by miqmago** [comment]
Ouch I see, maybe this is the reason why in mongo it does not appear the error string when saving the response in a collection...

What do you think to change `error` to `debugErrorObject` and make `error` an string? Don't know if this adds much value, if node-gcm is giving an error, maybe it is useful in order to dig inside library. Also I'm a little bit undecided about it...

**Comment by miqmago** [comment]
@alex-friedl what do you think of this?

When reviewing, I've realised that possibly the error was here: https://github.com/appfeel/node-pushnotifications/pull/86/files#diff-021cc9d7397993d75d0233af2d27d99eL83

```
error: new Error(failure.response.reason || failure.response),
```

This was passing `failure.response` to `new Error()` when no `failure.response.reason`.
But it was an object, right now I've replaced by `failure.status`

If you find it's all fine, for me it's ready to merge and publish.

**Comment by alex-friedl** [comment]
Hi @miqmago.
I like the general idea of having a property for the `Error` instance and one for the message.
But maybe it would be better to keep the `Error` in the `error` property and store the message in a `errorMsg` property? This way, we don't break any existing applications?

**Comment by alex-friedl** [comment]
Hi @miqmago,
Looks good upon first glance :)
I will try to look into your changes in detail this weekend.

**Pull request merged**
