### PR TITLE
adds silent push notification support for GCM

### PR DESCRIPTION
**Pull request by valeryq**
In continuation https://github.com/appfeel/node-pushnotifications/pull/42!
Changes compatible with this library https://github.com/zo0r/react-native-push-notification.
Not tested on native Android push notification libraries.
Can someone have ideas how to do it better?

@alex-friedl @appfeel

### CODE REVIEW

**Comment by noambonnie** [comment]
Is there anything I can do to help get this pull request merged? I could really use this functionality...

**Comment by alex-friedl** [comment]
Hello @valeryq,
thank your for your support!
I would prefer a solution without a new config flag, because it comes to down to the library not setting any unwanted fields and the user knowing which payload to use for silent push notifications.

I created a new branch and opened https://github.com/appfeel/node-pushnotifications/pull/83.

I don't have a working iOS setup for testing the feature, but could you maybe do so and give me feedback if this solution works for you? 

Thank you! :)

**Comment by valeryq** [comment]
@alex-friedl hi, ohh, I'm already forgot details. But yes, I think I can help in near future, because I also need a web push notification support in this library.

**Comment by alex-friedl** [comment]
Closed in favor of #83. Please let me know if everything works as expected and file an issue if something comes up :)

**Pull request closed without merging**
