### PR TITLE
Fixed test setup for GCM phonegap option

### PR DESCRIPTION
**Pull request by alex-friedl**

### CODE REVIEW

**Comment by appfeel** [comment]
Thanks, there is still missing tests when custom is string and when custom is something else (a number i.e.). In fact now that I read again the code, I see something not really nice there:

```
    let custom = typeof data.custom === 'string' ? { message: data.custom } : {};
    if (typeof data.custom === 'string') {
        custom = {
            message: data.custom,
        };
    } else if (typeof data.custom === 'object') {
        custom = Object.assign({}, data.custom);
    } else {
        custom = {
            data: data.custom,
        };
    }
```

What do you think if we change it to:

```
    let custom;
    if (typeof data.custom === 'string') {
        custom = {
            message: data.custom,
        };
    } else if (typeof data.custom === 'object') {
        custom = Object.assign({}, data.custom);
    } else {
        custom = {
            data: data.custom,
        };
    }
```

Would this affect to your branch? I propose that you implement this change and check if it's going to break your branch. Otherwise will

**Comment by alex-friedl** [comment]
Looks good to me and does not break any tests. I added your suggestion to this branch.

The missing tests you describe were missing all along then, weren't they? Could you just add them to the master on your own? I would really appreciate that :)

**Comment by appfeel** [comment]
Hmm... that's quite strange, the coverage before your branch was 100%... Are you sure that they were missing?

**Comment by alex-friedl** [comment]
I think so?

Coverage on commit 873238 (Release 1.0.14)

Statements   : 98.97% ( 193/195 )
Branches     : 94.63% ( 141/149 )
Functions    : 100% ( 42/42 )
Lines        : 98.9% ( 180/182 )

Coverage on commit 777182

Statements   : 98.99% ( 196/198 )
Branches     : 94.84% ( 147/155 )
Functions    : 100% ( 42/42 )
Lines        : 98.92% ( 183/185 )

**Comment by alex-friedl** [comment]
Thanks for merging! :)

Are you going to release 1.0.15 soon?

**Comment by appfeel** [comment]
Sure, I'm planning to implement the coverage remaining parts and publish (hope today, sure this week)

**Comment by alex-friedl** [comment]
Hi @appfeel 

any progress on your part? Would you consider releasing a new version without the missing coverage if you can't find the time to implement it?

Regards
Alex

**Comment by appfeel** [comment]
Thanks @alex-friedl, released :)

**Comment by alex-friedl** [comment]
Thank you! :)

**Comment by appfeel** [comment]
I'd be happy to add you in contributors section in package if you have time to pull request it as you wish :)

**Comment by alex-friedl** [comment]
I'd be happy to be added :)

What exactly do you need me to do? Not quite sure I understand :)

**Comment by appfeel** [comment]
:) a new pull request with a package.json modified: https://docs.npmjs.com/files/package.json#people-fields-author-contributors

```json
"contributors": [
  {
    "name": "optional",
    "email": "optional",
    "url": "optional"
  }
]
```

**Comment by alex-friedl** [comment]
Done! :)

https://github.com/appfeel/node-pushnotifications/pull/35

**Pull request merged**
