### PR TITLE
adds silent push notification support for APN - no conflicts!

### PR DESCRIPTION
**Pull request by DaveAdams88**
Decided to just create this pull request based off latest master branch changes - rather than figure out the conflicts in the other pull request! Let me know if there's anything else I can do to get this merged :)

### CODE REVIEW

**Comment by alex-friedl** [comment]
@appfeel Looks good to me. Would be nice to merge this :)

**Comment by appfeel** [comment]
I'm not really convinced if this functionality is up to the server or is the app who decides if it's silent or not... Any case, would'nt be the same if from the server you send `undefined.aif` in data.sound?

Also it's not really clear for me why the `notification.alert` depends too on `silent`. Any case, you can send a `data.custom: { silent: true }` and let decide the app how manages silent notifications.

**Comment by appfeel** [comment]
Ah! I see, this is for notifications when the app is killed, so no code from the app is executed, isn't it?

In that case, my doubts are on how to achieve the same behaviour on other platforms (Android, Windows Phone, etc)... As in that way, this functionality will be only available to ios, is that true?

**Comment by appfeel** [comment]
Any news regarding ios?

**Comment by jonas-arkulpa** [comment]
Hey guys,

we also depend on silent push notifications.
Are there any updates about this fix?
Or is there any workaround to allow silent push notifications for iOS with the current lib version?

Kind regards
Jonas

**Comment by noambonnie** [comment]
Is there anything I can do to help get this merged? I could really use this functionality.

**Comment by alex-friedl** [comment]
Closed in favor of #83. Please let me know if everything works as expected and file an issue if something comes up :)

**Pull request closed without merging**
